# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_auto_20160518_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 5, 22)),
        ),
    ]
